### ISSUE TITLE
Invoke the scan button functionality through our own UI.

### ISSUE THREAD

**Issue by dipti-agrawal** [mgriit/ScanAppForWeb#10]
Dear Team,
We want to invoke the scanning process through our own UI button.
Is there a possible way to start the scanning functionality without displaying the window form?

Any help would be much appreciated.

**Comment by mgriit** [comment]
Yup it is possible. You need to set all the default value. This process is done by Windows form  application.

**Comment by mgriit** [comment]
Yup it is possible. You need to set all the default value. This process is done by Windows form  application.
