### ISSUE TITLE
How to work with PHP application

### ISSUE THREAD

**Issue by hanijazzar** [mgriit/ScanAppForWeb#2]
So you mentioned in the Readme that ScanAppForWeb supports PHP appplication. Please could you give more info on that? What's the procedure for using the tool to scan for images and then upload them to a local server using PHP? Thanks

**Comment by mgriit** [comment]
Yes you can also add it to your PHP application. Just you have to Install  
[Scan_App_SetUp](https://github.com/mgriit/ScanAppForWeb/blob/master/DemoProject/SrcFile/Scan_App_SetUp.msi) to your PC where scanner connected and use the same HTML and JS at your HTML page like 
[Index](https://github.com/mgriit/ScanAppForWeb/blob/master/DemoProject/Views/Home/Index.cshtml)

**Comment by hanijazzar** [comment]
Okay yeah that was clear from the Readme, I was just asking if there is anything specific for PHP, but it seems it uses normal JS/PHP request/response. Thanks

**Comment by hanijazzar** [comment]
Okay so I'm trying to send my scanned image to the PHP backend, any idea which variable exactly should I send to the backend to be able to save the image as JPEG? is it the e.target.result in reader.onload? 
Here's my code

``
var value = {
                        scanned_image: reader.result
                    };
                    $.ajax(
                        {
                            url: "/upload-scanned-image",
                            type: "POST",
                            data: value,
                            success: function (data, textStatus, jqXHR)
                            {
                                console.log(data);
                            },
                            error: function (jqXHR, textStatus, errorThrown)
                            {

                                console.log("ERROR " + textStatus );
                                console.log(errorThrown);
                                console.log(jqXHR);
                            }
                        });

``
