### ISSUE TITLE
Donate to ScanAppForWeb 

### ISSUE THREAD

**Issue by CesarMarinAM** [mgriit/ScanAppForWeb#30]
Hi ScanAppForWeb team. Your solution was very util to my project.
So, Do you have a bank count to donate?, I want to give you some dollars.

**Comment by mgriit** [comment]
Thank you very much for using this repository. 
I have payoneer account. If you are from usa then use following bank detail. 
Bank name:
First Century Bank

Bank address:
1731 N Elm St  Commerce, GA 30529 USA

Routing (ABA):
061120084

Account number:
4023802573121

Account type:
CHECKING

Beneficiary name:
MD GOLAM RABBANY

If you are from other country plz let me know your country.
