### ISSUE TITLE
In which formate image is generating

### ISSUE THREAD

**Issue by nileshyadav326** [mgriit/ScanAppForWeb#4]
![image](https://user-images.githubusercontent.com/3830025/42429140-1ba433cc-8355-11e8-90c0-473f606510c7.png)
ab per above screenshot after scanning it doesn't specify the image type.
can u please add it.

it should be like below screenshort

![image](https://user-images.githubusercontent.com/3830025/42429221-7bb86ba2-8355-11e8-9732-7acc32ae3968.png)

**Comment by Notum** [comment]
I'm sorry for bumping up this issue, but can you provide some kind to convert scanned image to PNG or JPG file format?
