### ISSUE TITLE
How to reduce the clicks. Required two times click to scan.

### ISSUE THREAD

**Issue by nileshyadav326** [mgriit/ScanAppForWeb#5]
Hi, thanks for such an awesome plugin.
I have implemented this a webpage with scan button, whenever I click on the webpage scan button it opens a dialogue with button start scan and after clicking on start scan scanner is started and scanning the page. is there is anyway whenever I click on the webpage itself scan button scanner should start scanning the page.

**Comment by mgriit** [comment]
Second page for set up like page size, dpi, Simplex or Duplex etc. If We want to minimize scan size then we have to set default value.
