### ISSUE TITLE
Will this work with angular js?

### ISSUE THREAD

**Issue by gsoumakian** [mgriit/ScanAppForWeb#7]
Hi, 
Will this scan function work with an angular js application?

**Comment by mgriit** [comment]
Yes. This project use only Javascript at client side.

**Comment by gsoumakian** [comment]
Hi @mgriit, my team @dipti-agrawal and I are trying to implement your project into our application but we are having issues. I hope my team can share these issues with you.

**Comment by mgriit** [comment]
Ok i will try to help your team.

**Comment by gsoumakian** [comment]
Hi @mgriit. My team is converting your jQuery to angular, and they will share our code with you so you can add it to your project. Do you have a solution to convert your jpeg file to PDF? Also are you able to use your application with a scanner connected to a Chromebook?
